---
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

# This is the API URL to get the latest release
vsts_github_api: "https://api.github.com/repos/Microsoft/vsts-agent/releases/latest"

# If vsts_agent_fullurl is set this specific version will be downloaded instead of latest
# https://vstsagentpackage.azureedge.net/agent/2.129.0/vsts-agent-linux-x64-2.129.0.tar.gz
vsts_agent_version: "2.146.0"
vsts_agent_baseurl: "https://vstsagentpackage.azureedge.net/agent"
vsts_agent_file: "vsts-agent-linux-x64-{{vsts_agent_version}}.tar.gz"
vsts_agent_fullurl: "{{vsts_agent_baseurl}}/{{vsts_agent_version}}/{{vsts_agent_file}}"
vsts_agent_user: "deploy"

vsts_accountname: ""
vsts_poolname: ""
vsts_accesstoken: ""

vsts_server_url: "https://dev.azure.com/{{vsts_accountname}}"
vsts_agent_name: "{{ansible_hostname}}"
vsts_agentfolder: "/azdevops/{{vsts_agent_name}}"
vsts_workfolder: "{{vsts_agentfolder}}/_work/"

vsts_remove: false

runsvc_regex_fileline:
  - { regex: '^source /opt/rh/rh-git29/enable', line: 'source /opt/rh/rh-git29/enable'}
