---
#- import_tasks: install-python.yml
- name: Remove versoes anteriores do Docker
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Instala dependencias do Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add repositorio Docker
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes
