---
- import_tasks: Debian-config.yml
  when: ansible_os_family == 'Debian'

- name: Efetua a instalacao do Docker-CE
  package:
    name: docker-ce
    state: present
  notify: restart docker

- name: Habilita o Docker no Boot e inicia o serviço
  service:
    name: docker
    state: started
    enabled: yes
